/*
 *  This is a Portal Access for Client & Admin Usage
 *  (c) FGroupIndonesia, 2020-2021.
 */
package helper;

import beans.ExamMultipleChoice;

/**
 *
 * @author ASUS
 */
public class ExamMultipleChoiceDialog extends javax.swing.JDialog {

    /**
     * Creates new form ExamMultipleChoiceDialog
     */
    String text;
    boolean ansStat;

    public ExamMultipleChoice showFrame() {
        
        textfieldOptionTitle.requestFocus();
        
        setSize(345, 165);
        setVisible(true);
        text = textfieldOptionTitle.getText();

        ansStat = radioButtonYES.isSelected();
        ExamMultipleChoice data = null;

        // we use the data if only when the form is filled
        if (text.length() > 0) {

            data = new ExamMultipleChoice(text, labelOps.getText(), ansStat);

        }

        return data;

    }

    public ExamMultipleChoiceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public ExamMultipleChoiceDialog(java.awt.Frame parent, boolean modal, String opsUsed) {
        super(parent, modal);
        initComponents();

        labelOps.setText(opsUsed);

    }
    
    public ExamMultipleChoiceDialog(java.awt.Frame parent, boolean modal, String opsUsed, String defaultValue) {
        super(parent, modal);
        initComponents();

        
        labelOps.setText(opsUsed);
        textfieldOptionTitle.setText(defaultValue);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textfieldOptionTitle = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radioButtonYES = new javax.swing.JRadioButton();
        radioButtonNO = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        labelOps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textfieldOptionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldOptionTitleActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldOptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Is this the answer?"));

        buttonGroup1.add(radioButtonYES);
        radioButtonYES.setText("Yes");

        buttonGroup1.add(radioButtonNO);
        radioButtonNO.setSelected(true);
        radioButtonNO.setText("No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(radioButtonYES)
                .addGap(7, 7, 7)
                .addComponent(radioButtonNO)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonYES)
                    .addComponent(radioButtonNO))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 70));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, 30));

        labelOps.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelOps.setText("A");
        getContentPane().add(labelOps, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, 40, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textfieldOptionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldOptionTitleActionPerformed
        this.dispose();
    }//GEN-LAST:event_textfieldOptionTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamMultipleChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamMultipleChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamMultipleChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamMultipleChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExamMultipleChoiceDialog dialog = new ExamMultipleChoiceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelOps;
    private javax.swing.JRadioButton radioButtonNO;
    private javax.swing.JRadioButton radioButtonYES;
    private javax.swing.JTextField textfieldOptionTitle;
    // End of variables declaration//GEN-END:variables
}
